#!/usr/bin/env node
// Generate the map's text twin.
//
//   node scripts/twin.mjs <map>.json --repo <root> --out SYSTEM.md
//
// The same system-map.json that draws the page also writes a document. One
// source, two views, so they cannot disagree -- and the text one is the view
// that survives a code review, a grep, a diff between two commits, and a
// terminal with no browser. The picture is better for grasping shape; this is
// better for everything you do afterwards.
//
// Every claim carries the citation the gate already verified, which is the part
// a hand-written architecture document never has.

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { validateMap, resolveNodeFiles, scopeCoverage } from './validate.mjs'
import { massOf } from './lib/geometry.mjs'

const KIND_LABEL = {
  entry: 'entry point', service: 'service', store: 'store', queue: 'buffer',
  worker: 'worker', external: 'outside this repo', config: 'types and constants', ui: 'client',
}

const EDGE_VERB = {
  call: 'calls', read: 'reads from', write: 'writes to', emit: 'publishes to',
  consume: 'consumes from', http: 'reaches over the network', import: 'imports types from',
}

const cite = (c) => `\`${c.file}:${c.line}\` — \`${c.evidence.replace(/`/g, "'")}\``

export async function twin(map, repoRoot) {
  const { resolved } = await resolveNodeFiles(map, repoRoot)
  const coverage = await scopeCoverage(map, repoRoot)
  const byId = new Map(map.nodes.map((node) => [node.id, node]))
  const out = []
  const w = (line = '') => out.push(line)

  const totals = Object.values(resolved).reduce(
    (acc, entry) => ({ files: acc.files + entry.fileCount, loc: acc.loc + entry.loc }),
    { files: 0, loc: 0 },
  )

  // ---- header --------------------------------------------------------------
  w(`# ${map.meta.title}`)
  w()
  if (map.meta.subtitle) { w(`*${map.meta.subtitle}*`); w() }
  w(`| | |`)
  w(`|---|---|`)
  w(`| Repository | \`${map.meta.repository}\` |`)
  w(`| Revision | \`${map.meta.branch || 'main'}\` @ \`${map.meta.commit}\` |`)
  w(`| Structures | ${map.nodes.length} in ${map.groups.length} districts |`)
  w(`| Connections | ${map.edges.length} |`)
  w(`| Measured | ${totals.files} source files, ${totals.loc.toLocaleString()} lines |`)
  if (coverage) w(`| Scope coverage | ${coverage.claimed}/${coverage.inScope} files claimed |`)
  if ((map.chapters ?? []).length > 0) w(`| Chapters | ${map.chapters.length} |`)
  w(`| Traced flows | ${(map.flows ?? []).length} |`)
  w()
  w(`> Generated from \`system-map.json\`. Do not edit this file — edit the map and`)
  w(`> regenerate, or the two views will disagree. Every citation below was`)
  w(`> verified against the revision named above at generation time.`)
  w()

  // ---- overview ------------------------------------------------------------
  w(`## What this is`)
  w()
  for (const para of map.meta.overview.split(/\n{2,}/)) w(`${para.trim().replace(/\s+/g, ' ')}\n`)
  w(`**Scope.** ${map.meta.scope}`)
  w()
  if (map.meta.omitted) {
    w(`**Not shown.** ${map.meta.omitted.edges} connection(s) left off: ${map.meta.omitted.note}`)
    w()
  }

  // ---- reading order -------------------------------------------------------
  if ((map.chapters ?? []).length > 0) {
    w(`## How to read this`)
    w()
    w(`The map reveals the system a few structures at a time. This is that order,`)
    w(`so the document can be read the same way.`)
    w()
    map.chapters.forEach((chapter, index) => {
      w(`### ${index + 1}. ${chapter.title}`)
      w()
      w(`*${chapter.lede}*`)
      w()
      for (const para of chapter.story.split(/\n{2,}/)) w(`${para.trim().replace(/\s+/g, ' ')}\n`)
      if ((chapter.reveals ?? []).length > 0) {
        w(`**Introduces.** ${chapter.reveals.map((id) => `[${byId.get(id)?.label ?? id}](#${
          byId.has(id) ? anchor(byId.get(id)) : id})`).join(', ')}`)
      } else {
        w(`**Introduces.** Nothing new — this is the whole system at once.`)
      }
      w()
      if (chapter.flow) {
        const flow = (map.flows ?? []).find((entry) => entry.id === chapter.flow)
        if (flow) w(`**Flow shown.** ${flow.label} — ${flow.summary}\n`)
      }
    })
  }

  // ---- the structures at a glance -----------------------------------------
  w(`## Structures`)
  w()
  const fanIn = new Map(map.nodes.map((node) => [node.id, 0]))
  for (const edge of map.edges) fanIn.set(edge.to, (fanIn.get(edge.to) ?? 0) + 1)
  for (const group of [...map.groups].sort((a, b) => (a.order ?? 0) - (b.order ?? 0))) {
    const members = map.nodes.filter((node) => node.group === group.id)
    if (members.length === 0) continue
    w(`### ${group.label}`)
    w()
    w(`| | Structure | Kind | Files | Lines | Depended on by |`)
    w(`|---|---|---|---|---|---|`)
    for (const node of members) {
      const m = resolved[node.id]
      w(`| \`${node.id}\` | [${node.label}](#${anchor(node)}) | ${KIND_LABEL[node.kind] ?? node.kind}`
        + ` | ${m.fileCount} | ${m.loc.toLocaleString()} | ${fanIn.get(node.id) ?? 0} |`)
    }
    w()
  }

  // ---- one section per structure ------------------------------------------
  w(`## Structures in detail`)
  w()
  for (const node of map.nodes) {
    const m = resolved[node.id]
    const mass = massOf(m)
    w(`### ${node.label} \`${node.id}\``)
    w()
    w(`${KIND_LABEL[node.kind] ?? node.kind}`
      + (node.confidence === 'inferred' ? ' · **inferred**' : '')
      + ` · ${m.fileCount} files · ${m.loc.toLocaleString()} lines`
      + (mass.capped ? ` · height capped at 30 (really ${mass.rawFloors} floors of code)` : ''))
    w()
    w(node.whatItDoes.replace(/\s+/g, ' '))
    w()
    w(`**How it's built.** ${node.howItsBuilt.replace(/\s+/g, ' ')}`)
    w()
    if ((node.concerns ?? []).length > 0) {
      w(`**Concerns.**`)
      for (const concern of node.concerns) w(`- ${concern}`)
      w()
    }
    const out_ = map.edges.filter((edge) => edge.from === node.id)
    const in_ = map.edges.filter((edge) => edge.to === node.id)
    if (out_.length > 0 || in_.length > 0) {
      w(`**Connections.**`)
      for (const edge of out_) {
        w(`- ${EDGE_VERB[edge.kind] ?? edge.kind} **${byId.get(edge.to)?.label ?? edge.to}**`
          + (edge.label ? ` (${edge.label})` : '')
          + (edge.confidence === 'inferred' ? ' — *inferred*' : '')
          + `<br>${cite(edge.citation)}`)
      }
      for (const edge of in_) {
        w(`- ← **${byId.get(edge.from)?.label ?? edge.from}** ${EDGE_VERB[edge.kind] ?? edge.kind} this`)
      }
      w()
    }
    w(`**Evidence.**`)
    for (const citation of node.citations) w(`- ${cite(citation)}`)
    w()
    w(`**Files.** \`${node.files.join('`, `')}\``)
    w()
  }

  // ---- flows ---------------------------------------------------------------
  if ((map.flows ?? []).length > 0) {
    w(`## Traced flows`)
    w()
    for (const flow of map.flows) {
      w(`### ${flow.label}`)
      w()
      w(flow.summary)
      w()
      if (flow.trigger) w(`**Trigger.** ${flow.trigger}\n`)
      if (flow.payload) w(`**Payload.** \`${flow.payload}\`\n`)
      flow.steps.forEach((step, index) => {
        const from = byId.get(step.from)?.label ?? step.from
        const to = byId.get(step.to)?.label ?? step.to
        w(`${index + 1}. **${from} → ${to}**${step.branch ? ' *(side effect; the path does not advance)*' : ''}`)
        w(`   ${step.note}`)
        w(`   ${cite(step.citation)}`)
      })
      w()
    }
  }

  // ---- provenance ----------------------------------------------------------
  w(`## Provenance`)
  w()
  const inferredNodes = map.nodes.filter((node) => node.confidence === 'inferred')
  const inferredEdges = map.edges.filter((edge) => edge.confidence === 'inferred')
  w(`Every structure, connection and flow step above cites a file, a line, and a`)
  w(`literal string found at that line. The map is rejected at build time until`)
  w(`all of them resolve, so this document cannot drift from the code silently —`)
  w(`it can only fail to build.`)
  w()
  w(`What the check does **not** cover: it proves a cited line exists and says`)
  w(`what is quoted, not that it was read correctly. Interpretation is human.`)
  w()
  if (inferredNodes.length + inferredEdges.length > 0) {
    w(`**Marked inferred** (real, but not pinnable to one line):`)
    for (const node of inferredNodes) w(`- structure \`${node.id}\` ${node.label}`)
    for (const edge of inferredEdges) w(`- \`${edge.from}\` → \`${edge.to}\``)
    w()
  } else {
    w(`Nothing is marked inferred: every relationship is pinned to a line.`)
    w()
  }
  if (coverage && coverage.unclaimed.length > 0) {
    w(`**In scope but claimed by no structure** (${coverage.unclaimed.length} files):`)
    for (const [dir, count] of coverage.clusters.slice(0, 10)) w(`- ${count} in \`${dir}\``)
    w()
  }
  return `${out.join('\n').replace(/\n{3,}/g, '\n\n')}\n`
}

function anchor(node) {
  return `${node.label} ${node.id}`.toLowerCase().replace(/[^a-z0-9 -]/g, '').replace(/\s+/g, '-')
}

const isMain = process.argv[1] && resolve(process.argv[1]).endsWith('twin.mjs')
if (isMain) {
  const args = process.argv.slice(2)
  const flags = new Map()
  const positional = []
  for (let i = 0; i < args.length; i += 1) {
    if (args[i].startsWith('--')) { flags.set(args[i].slice(2), args[i + 1]); i += 1 } else positional.push(args[i])
  }
  if (!positional[0] || !flags.has('out')) {
    console.error('usage: node scripts/twin.mjs <map.json> --repo <root> --out SYSTEM.md')
    process.exit(2)
  }
  const repoRoot = resolve(flags.get('repo') ?? process.cwd())
  const map = JSON.parse(readFileSync(resolve(positional[0]), 'utf8'))
  const gate = validateMap(map, repoRoot)
  if (gate.errors.length > 0) {
    console.error(`map failed validation:\n${gate.errors.map((e) => `  ${e}`).join('\n')}`)
    process.exit(1)
  }
  const text = await twin(map, repoRoot)
  writeFileSync(resolve(flags.get('out')), text, 'utf8')
  console.log(`wrote ${flags.get('out')} (${(text.length / 1024).toFixed(1)} KB, ${text.split('\n').length} lines)`)
}
